### ISSUE TITLE
Unexpected code Response when running CPT4 post process on Athena Download

### ISSUE THREAD

**Issue by jstroup** [OHDSI/Athena#283] opened 2022-06-08 19:41 UTC
Hi,

We've never had this problem before when doing the CPT4 post process? Can anyone shed light on what may have changed in the CPT4 jar? When we access the URL directly we also get a 401 response. 

Thanks,
Jeff

C:\Users\stroupj\Documents\Projects\Active Projects\OMOP\Athena Downloads\v5.0 02-JUN-22>java -Dumls-apikey=<...> -jar cpt4.jar 5
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[ERROR] 2022-06-08 15:20:21.330 [main] Application - Unexpected code Response{protocol=h2, code=401, message=, url=https://utslogin.nlm.nih.gov//cas/v1/api-key}
org.odhsi.utils.cpt.Cpt4Exception: Unexpected code Response{protocol=h2, code=401, message=, url=https://utslogin.nlm.nih.gov//cas/v1/api-key}
        at org.odhsi.utils.cpt.restclient.RestTicketClient.checkSuccessful(RestTicketClient.java:76) ~[cpt4.jar:?]
        at org.odhsi.utils.cpt.restclient.RestTicketClient.requestTGT(RestTicketClient.java:64) ~[cpt4.jar:?]
        at org.odhsi.utils.cpt.restclient.RestTicketClient.build(RestTicketClient.java:55) ~[cpt4.jar:?]
        at org.odhsi.utils.cpt.Application.main(Application.java:32) [cpt4.jar:?]
Exception in thread "main" org.odhsi.utils.cpt.Cpt4Exception: Cannot process CONCEPT.csv file. You can find more details in the logs/logfile.log file.
Reason: Unexpected code Response{protocol=h2, code=401, message=, url=https://utslogin.nlm.nih.gov//cas/v1/api-key}
        at org.odhsi.utils.cpt.Application.main(Application.java:45)

**Comment by mik-ohdsi** [comment] 2022-06-15 16:56
Hi @jstroup - we had issues with the cpt4.jar but AFTER the process had actually been finished, on closing the connection it seems. This one is new. I will download and test myself to reproduce this behavior!

**Comment by mik-ohdsi** [comment] 2022-06-20 16:49
Hi @jstroup - I cannot reproduce this issue here. I only get the known errors AFTER the conversion has completed:
C:\Users\[...]\downloads\vocabulary_download_v5_20220617_cpt4test>cpt.bat {my UMLS API key}
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2022-06-20 17:33:10.135 [main] ConceptService - Writing updated data to CONCEPT.csv
Updated CPT4 records:  **16615/16615**
[INFO ] 2022-06-20 18:08:12.100 [main] ConceptService - All cpt4 concepts are processed.
Exception in thread "main" org.odhsi.utils.cpt.Cpt4Exception: Unexpected code Response{protocol=h2, code=401, message=, url=https://utslogin.nlm.nih.gov//cas/v1/tickets/TGT-1547862-pyyp475l4mwd3ej-cas}
        at org.odhsi.utils.cpt.restclient.RestTicketClient.checkSuccessful(RestTicketClient.java:76)
        at org.odhsi.utils.cpt.restclient.RestTicketClient.logout(RestTicketClient.java:113)
        at org.odhsi.utils.cpt.restclient.RestTicketClient.close(RestTicketClient.java:125)
        at org.odhsi.utils.cpt.Application.main(Application.java:49)

Maybe a temporary glitch with the NLM API? Can you try again? If you run into another error again, maybe consider updating your Java Runtime Environment?
Thanks - mik

**Comment by mik-ohdsi** [comment] 2022-07-07 22:12
Hi @jstroup  -  can you confirm that you still run into this problem? Have you tried it again, maybe updated your JRE? If I do not hear from you, we will close this issue in due time.

**Comment by mik-ohdsi** [comment] 2022-07-21 14:16
Hi @jstroup - there is a chance that your user has expired with UMLS (did you complete the yearly survey?) and hence your APIKey is not accepted anymore?

**Comment by mik-ohdsi** [comment] 2022-09-05 11:57
Hi @jstroup - assuming that your problem was fixed somehow based on our recommendations, we close this issue now. It would still be very useful if you would tell us what fixed your problem so that other users can benefit from this information. Thanks!

**Closed by mik-ohdsi** 2022-09-05 11:57 UTC

**Comment by jstroup** [comment] 2022-10-05 18:40
Hi @mik-ohdsi ,

I did renew my expired UMLS and used the new api-key successfully. Some allusion to that in the error message might help.  Sorry for not responding earlier. I ran into this again today after running code that used the old key. Thanks!
