### ISSUE TITLE
small redesign of the search page 

### ISSUE THREAD

**Issue by YaroslavTir** [OHDSI/Athena#120] opened 2020-03-27 13:51 UTC
Redesign Athens home(search) page:

- by default the overview table is not showing, there are no any results. 
- add shortcut buttons for search by
-- Drugs domain
-- Conditions domain
-- Procedures domain
-- Devices domain
-- Observations domain
-- Measurements domain

example: 
![image](https://user-images.githubusercontent.com/3305166/77762743-479b5e00-703a-11ea-9d43-8129b20c72a8.png)

**Comment by acumarav** [comment] 2020-05-25 14:24
closing as duplicate of the OHDSI/AthenaUI#69

**Closed by acumarav** 2020-05-25 14:24 UTC
