### ISSUE TITLE
New search algorithm unexpected results - let's collect here all our concerns about new search

### ISSUE THREAD

**Issue by ekorchmar** [OHDSI/Athena#82] opened 2019-10-02 09:24 UTC
Examples:

1. http://athena.ohdsi.org/search-terms/terms?query=lucitanib&page=1
Found unrelated concepts with different spelling.

2. http://athena.ohdsi.org/search-terms/terms?query=diabetes&page=1&sort=concept_name&order=asc
Search for "diabetes" provides concepts with matches with as few as 3 matching characters with no way to sort for correct matches first.

3. http://athena.ohdsi.org/search-terms/terms?query=cryo+plasma&page=1
First result shown is "Creo Pharma Ltd" which is mismatched on both words. Expected cryoprecipitate plasma products to show up first.

Please consider giving an option to sort by direct matches first or adding an indication which search results are fuzzy matches.

**Comment by dimshitc** [comment] 2019-10-02 09:46
Let's make it clear:
- use case description (if input below is not self-explanatory)
- expected behaviour
- link with an actual output

**Comment by dimshitc** [comment] 2019-10-02 09:49
- want to find all the concept codes containing "1296@"
- want to see '1296@90', '1296@95', etc
- instead I got http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=15&query=1296%40

**Comment by Alexdavv** [comment] 2019-10-02 10:43
Glucose-6-phosphate dehydrogenase has several writing forms:
- Glucose-6-phosphate dehydrogenase (concept_id 40343462)
- Glucose 6-phosphate dehydrogenase (concept_id 37398675)
- Glucose 6 phosphate dehydrogenase (concept_id 45911804)

Neither of these search queries retrieves all of them.
[Glucose-6-phosphate dehydrogenase](http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=50&query=Glucose-6-phosphate+dehydrogenase)
[Glucose 6-phosphate dehydrogenase](http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=50&query=Glucose+6-phosphate+dehydrogenase)
[Glucose 6 phosphate dehydrogenase](http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=50&query=Glucose+6+phosphate+dehydrogenase)
[Glucose6phosphate dehydrogenase](http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=50&query=Glucose6phosphate+dehydrogenase)

So still need to use multiple queries.

One more thing - why users even should know that **dehydrogenase** is always a separate word?
These queries retrieve nothing:
[Glucose-6-phosphate-dehydrogenase](http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=50&query=Glucose-6-phosphate-dehydrogenase)
[Glucose6phosphatedehydrogenase](http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=50&query=Glucose6phosphatedehydrogenase)

**Comment by MelaniePhilofsky** [comment] 2019-10-16 20:31
Searched for domain = drug,  standard = standard, vocabulary = CVX, search term = haemophilus influ
Returned drugs with vocabulary = RxNorm

link [here](http://athena.ohdsi.org/search-terms/terms?domain=Drug&standardConcept=Standard&vocabulary=CVX&vocabulary=RxNorm&page=1&pageSize=50&query=haemophilus+influ) 

Screen shot:
<img width="1250" alt="Screen Shot 2019-10-16 at 2 26 35 PM" src="https://user-images.githubusercontent.com/22457958/66956383-8b1c8580-f021-11e9-9783-4a27372e3ce5.png">

**Comment by Alexdavv** [comment] 2019-10-17 07:26
> Searched for domain = drug, standard = standard, vocabulary = CVX, search term = haemophilus influ
> Returned drugs with vocabulary = RxNorm

It's just a UI issue, which we meet from time to time and should be probably addressed separately. When you apply/cancel a filter, then start new search, but the entire query and HTTP ignores your last filter changes.
Just check your query, RxNorm is still active there.

BTW, you are really lucky since Athena understand your 'influ'. In most cases, we have to spell out everything now.

**Comment by MelaniePhilofsky** [comment] 2019-10-17 13:54
Thanks, @Alexdavv ! I have noticed the UI has been "buggy" lately. Sometimes I have to open a new browser because the logging of my previous search  mixes with my current search and I get 0 results on new searches. Where should I report the UI issues?

**Comment by Alexdavv** [comment] 2019-10-26 10:35
@olga-ganina Where @MelaniePhilofsky can report [this](https://github.com/OHDSI/Athena/issues/82#issuecomment-543185982)?

Another think - searching among synonyms:
[Search for 'SVT'](http://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&page=1&pageSize=15&query=SVT).
See 7854 concepts, but without 'SVT' in the name.
And then [desired concept](http://athena.ohdsi.org/search-terms/terms/4275423) on the last (7855th) position. It has full match 'SVT' in the concept_synonym_name.

**Comment by ekorchmar** [comment] 2019-11-04 13:35
http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=15&query=4030314

Concept_id = 4030314 should have precedence over Concept_code = 4030314

**Comment by Alexdavv** [comment] 2019-11-04 15:06
> http://athena.ohdsi.org/search-terms/terms?page=1&pageSize=15&query=4030314
> 
> Concept_id = 4030314 should have precedence over Concept_code = 4030314

Why? Concept_id is better than a code? Or Standard concept is better than a non-Standard one.
Can you please refer to such searching rules?

**Comment by ekorchmar** [comment] 2019-11-04 15:16
Concept code can be ambiguous across vocabularies (and in some cases even inside of one), so concept_id is a better identifier for a concept.

Also the idea of giving standard concepts higher preference seems good too.

**Comment by Alexdavv** [comment] 2019-11-04 15:57
But this is for search algorithm’s further improvements (not even expected to be in this release).
But agree, there is no such thread anymore, lets collect together.

**Comment by cgreich** [comment] 2019-11-06 10:09
Couple of findings:
Search:
- When the search can find a keyword exactly, it is listed before the fuzzy matches and synonym matches. That's good. But it is not clear how the results are sorted. I would definitely sort by standard (first standard, then classification, then non-standard).
- But the problems start when there is no precise match: There is no distinction if something was found in the synonyms, or if something was found that's spelled differently. This needs to be obvious in the UI.
- When a spelling cannot be found, but an alternative close spelling gets good results, we should do like Google and say "Do you mean XXX?", or "Didn't find XXX, but found YYY".
- The fuzzy matching engine works in strange way: searching for "methamizole" finds "metamizole" and "methimazole", but "metimazole" only finds "methimazole", even though the edit distance is the same.
- Also, the fuzzy matching should work stricter. For example, searching for "metimaz" finds "ketamin". 

Navigation:
- When following a relationship and clicking on a destination concept, loading of that concept is very slow. And the funny thing is, you can already see all the relationship of the concept to be displayed in grey, while the wheel is still spinning. However, the concept details are not yet available. Is it really possible that the CONCEPT_RELATIONSHIP table can be read instantaneously, but the CONCEPT table takes 5 seconds?
- The page list should be on the bottom also, not just on the top. Because what happens is that folks will scroll down and then want to do next page, without having to scroll all the way up.
- The sorting function (clicking on a column name) seems to be working case sensitive, should be insensitive.

**Comment by Alexdavv** [comment] 2019-11-06 12:35
> * The page list should be on the bottom also, not just on the top. Because what happens is that folks will scroll down and then want to do next page, without having to scroll all the way up.

Even better it might be [a fixed panel](https://github.com/Tsemharb/AthenaCrutches/blob/f908e48a91f3ce92375e82ed5f36a129c7ba635f/content.js#L13).
![image](https://user-images.githubusercontent.com/32357692/68296811-825e2300-00a6-11ea-9b08-0cabbc41e4d5.png)


Another useful thing - [copying of the full concept string by clicking on the area outside the link text](https://github.com/Tsemharb/AthenaCrutches/blob/f908e48a91f3ce92375e82ed5f36a129c7ba635f/content.js#L33).

This is what we're [doing](https://github.com/Tsemharb/AthenaCrutches/blob/master/content.js) on the user's side through the Chrome extension.
It would be good to implement.

**Comment by acumarav** [comment] 2020-05-21 11:39
> @olga-ganina Where @MelaniePhilofsky can report [this](https://github.com/OHDSI/Athena/issues/82#issuecomment-543185982)?
> 
> Another think - searching among synonyms:
> [Search for 'SVT'](http://athena.ohdsi.org/search-terms/terms?standardConcept=Standard&page=1&pageSize=15&query=SVT).
> See 7854 concepts, but without 'SVT' in the name.
> And then [desired concept](http://athena.ohdsi.org/search-terms/terms/4275423) on the last (7855th) position. It has full match 'SVT' in the concept_synonym_name.

Currently, we are testing 1.11 - for the provided case it gives 4 results with the desired one on the  top. I hope it will solve the issue:
![image](https://user-images.githubusercontent.com/7705583/82555627-6153b000-9b68-11ea-9629-17c8b69342e6.png)

**Comment by acumarav** [comment] 2020-05-21 11:46
> Searched for domain = drug, standard = standard, vocabulary = CVX, search term = haemophilus influ
> Returned drugs with vocabulary = RxNorm
> 
> link [here](http://athena.ohdsi.org/search-terms/terms?domain=Drug&standardConcept=Standard&vocabulary=CVX&vocabulary=RxNorm&page=1&pageSize=50&query=haemophilus+influ)
> 
> Screen shot:
> <img alt="Screen Shot 2019-10-16 at 2 26 35 PM" width="1250" src="https://user-images.githubusercontent.com/22457958/66956383-8b1c8580-f021-11e9-9783-4a27372e3ce5.png">

This is visual bug, I fixed it in the 1.11 which will be released soon. If you look into the link you've posted RxNorm is there but not on the screen.

**Comment by acumarav** [comment] 2020-05-21 12:01
>     * 1296@95

Hello @dimshitc,
For this case 1.11 will offer improved * functionality which  will give only one page of results which includes both you are looking for: [our_qa](https://qaathena.odysseusinc.com/search-terms/terms?query=1296%40%2A&boosts&page=1)

**Comment by acumarav** [comment] 2020-11-04 07:38
Closing as the search functionality was reworked in the Athena 1.11 release

**Closed by acumarav** 2020-11-04 07:38 UTC
