### ISSUE TITLE
Process non-standard ASCII characters correctly

### ISSUE THREAD

**Issue by cgreich** [OHDSI/Athena#86] opened 2019-11-21 07:50 UTC
For example, the name of user mbarbe@gmail.com is "Barbé", not "Barb��".

**Comment by acumarav** [comment] 2020-03-03 12:56
The issue is caused by the CAS component and can be fixed without Athena release

**Comment by acumarav** [comment] 2020-03-03 13:13
Test: 
https://drive.google.com/file/d/1nWB_zbYOM2o8XNfMsnuS9cQrz8m_ruj1/view?usp=sharing

**Closed** 2020-07-13 15:41 UTC
Labels: bug
