### ISSUE TITLE
Some invalid concepts are not loaded in /search-terms/terms/${concept_id} view

### ISSUE THREAD

**Issue by ekorchmar** [OHDSI/Athena#391] opened 2024-07-16 08:40 UTC
## Example:
https://athena.ohdsi.org/search-terms/terms/40317576

## Expected behavior
Left pane is populated with data

## Actual behavior
![image](https://github.com/user-attachments/assets/211144d0-7828-400e-a456-f45eee7363cb)

## Additional details
I am not well versed in Java, but it looks like processor of [this query](https://github.com/OHDSI/Athena/blob/d2394edd91a59d022b6c0f19026116276647132c/src/main/java/com/odysseusinc/athena/repositories/v5/ConceptV5Repository.java#L35) result is not equipped to handle multiple 'Maps to' replacements. Of course, it is not valid for the concept 40317576 to have multiple mapping targets, but other concepts might have multiple valid mappings; this needs to be handled.

**Comment by Alexdavv** [comment] 2024-07-24 16:02
A duplicate of https://github.com/OHDSI/Athena/issues/270

**Closed by Alexdavv** 2024-07-24 16:02 UTC
